name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
      - name: install serve for running production build
        run: npm install serve
      - name: test e2e
        uses: cypress-io/github-action@v2
        with:
          command: npx cypress run
          start: serve -s build
          wait-on: http://localhost:3000
