name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build

      - name: test e2e
        uses: cypress-io/github-action@v2
        with:
          command: npx cypress run
          start: npm run start:test
          wait-on: http://localhost:3000
          env: REACT_APP_API_PROD_URL=https://powerful-mountain-41188.herokuapp.com/api
