name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: npm install
        run: npm install

      - name: lint
        run: npm run lint

      - name: build
        run: npm run build
        env:
          REACT_APP_API_PROD_URL: https://powerful-mountain-41188.herokuapp.com/api

      - name: install serve for running production build
        run: npm install serve

      - name: test e2e
        uses: cypress-io/github-action@v2
        with:
          command: npx cypress run
          start: npm run start:prod
          wait-on: http://localhost:3000
        env:
          CYPRESS_REACT_APP_API_PROD_URL: https://powerful-mountain-41188.herokuapp.com/api

      - name: debloy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'tranquil-beyond-71839'
          heroku_email: 'ville.l.alatalo@gmail.com'
        env:
          HD_REACT_APP_API_PROD_URL: https://powerful-mountain-41188.herokuapp.com/api
